### PR TITLE
fix: Upgrade to Raygun4Net 11.0.3

### PR DESCRIPTION
**Pull request by miquelbeltran**
This fixes https://raygun.com/forums/thread/186975#187021

### CODE REVIEW

**Review by ProRedCat — CHANGES_REQUESTED** [review]
Can we add a change log entry

**Comment by miquelbeltran** [comment]
I think I updated the version at the right places.

The changelog line is the same that can be found in the raygun4net changelog.

**Comment by ProRedCat** [comment]
All looks good now, I'll get a pre-release out so it can be tested to confirm the issue is fixed

**Review by ProRedCat — APPROVED** [review]
Pre-release confirmed that this issue is fixed

**Pull request merged**
